title = 'SaltWater'

contentDir = 'content/zh'
languageName = 'ç®€ä½“ä¸­æ–‡'
languageCode = 'zh-Hans-CN'

copyright = 'ç‰ˆæƒæ‰€æœ‰'

weight = 1

[params]
    author = 'NotHimmel'
    description = 'ğŸ'